### ISSUE TITLE
How to use shortcut key to insert code block instead of package control

### ISSUE THREAD

**Issue by ShuaidongGG** [molnarmark/markdowncodeblocks#2]
As title, add key bindings is really important for lazy boy(like me).

**Comment by molnarmark** [comment]
Hi, something like this should do it.

```json
{ "keys": ["f4"], "command": "markdown_add_code_block" }
```

**Comment by ShuaidongGG** [comment]
hah, thanks, i read your source code and find `"command": "markdown_add_code_block" `, and i add this code in Key Bindings 
```
[
...
{
    "keys": ["ctrl+shift+g"],
    "command": "markdown_add_code_block"
},
...
]
```
Anyway, thanks very much :) 👍
